[package]
name = "perf-rust"
version = "0.1.0"
authors = ["Briana Oursler <briana.oursler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
thiserror= "1.0.24"
